tasks:
  - name: add-label
    on:
      issues:
        types: [opened]
    config:
      label: 'triage'
  - name: remove-label
    on:
      issue_comment:
        types: [created]
    config:
      label: 'needs reply'
      exclude-labeler: true
  - name: add-platform-labels
    on:
      issues:
        types: [opened, edited]
  - name: assign-to-project
    on:
      issues:
        types: [opened]
      pull_request:
        types: [opened]
    condition: (await getTeamMembers('capacitor')).includes(payload.sender.login)
    config:
      columns:
        issue: 10495656
        pr: 10495659
        draft-pr: 10495658
