tasks:
  - name: add-label
    on:
      issues:
        types: [opened]
    config:
      label: 'triage'
  - name: remove-label
    on:
      issue_comment:
        types: [created]
    config:
      label: 'needs reply'
      exclude-labeler: true
  - name: add-platform-labels
    on:
      issues:
        types: [opened, edited]
