
# This workflow is a WIP to get the plugins to deploy to cocoapods
# Its put on hold as it's currently failing during the pod trunk push command
# See the docs on how to run during manual deployment

# name: Cocoapods Deploy

# on:
#   workflow_dispatch:

# jobs:
#   deploy-cocoapods:
#     runs-on: macos-latest
#     timeout-minutes: 30
#     steps:
#       - uses: actions/setup-node@v1
#         with:
#           node-version: 14.x
#       - uses: actions/checkout@v2
#         with:
#           fetch-depth: 0
#       - name: Install Cocoapods
#         run: | 
#           gem install cocoapods
#       - name: Restore Dependency Cache
#         id: cache-modules
#         uses: actions/cache@v2
#         with:
#           path: |
#             node_modules
#             */node_modules
#           key: dependency-cache-${{ hashFiles('package.json', '*/package.json') }}
#       - run: npm install
#       - name: Deploy to Cocoapods
#         run: |
#           set -eo pipefail
#           npm run publish:cocoapod
#         env:
#           COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}