platform :ios, '13.0'

def capacitor_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
end

target 'Plugin' do
  capacitor_pods
  pod 'GoogleMaps', '~> 7.4'
  pod 'Google-Maps-iOS-Utils', '~> 4.2'
end

target 'PluginTests' do
  capacitor_pods
  pod 'GoogleMaps', '~> 7.4'
  pod 'Google-Maps-iOS-Utils', '~> 4.2'
end
